### ISSUE TITLE
Does not work with stack: base >= 4.13 can not be found

### ISSUE THREAD

**Issue by bneijt** [georgefst/evdev#1]
The cabal file says
```
    base  >= 4.13.0 && < 4.14,
```
But that release does not exist on hackage yet http://hackage.haskell.org/package/base ?

I would love for the following to work:
```
git clone git@github.com:georgefst/evdev.git
cd evdev
stack init
```
Could you publish a release which works like that with stack?

**Comment by bneijt** [comment]
Just found out that `nightly-2019-11-29` works except for `streamly` which has a newer release.
I'm still confused about `base` not being there and I would still love `evdev` to work with an LTS stack resolver, but for now I can get it working with stack if I allow for an upgrade of streamly.

**Comment by bneijt** [comment]
I'm sending in a pull request to get a newer version of streamly allowed, with that the nightly-2019-11-29 snapshot works well.

**Comment by georgefst** [comment]
I should actually really lower the bound on `base`. I happened to be using GHC 8.8 while developing this, but it seems 8.6 is safer to use for now for various reasons. I don't personally use `stack` so I didn't have this particular issue.
