### ISSUE TITLE
libevdev_get_uniq and libevdev_get_phys could return NULL

### ISSUE THREAD

**Issue by kamoii** [georgefst/evdev#15]
According to [document](https://www.freedesktop.org/software/libevdev/doc/0.5/group__bits.html#ga5df483b0b24d7b96ea1181808fab851d), `libevdev_get_uniq` and `libevdev_get_phys` could return NULL.  `deviceUniq` and `devicePhys` fails with SIGSEGV error when NULL is returned.

**Comment by georgefst** [comment]
Oof, sorry, that's a bit careless on my part - I've barely used those functions.

It's an easy fix to make them return `Maybe`s. I can probably manage that this evening.

**Comment by kamoii** [comment]
@georgefst Ah, thanks for your fast reply. Noticed your reply after I sent PR.

**Comment by georgefst** [comment]
No worries - you fixing it yourself is even better!

**Comment by georgefst** [comment]
Closed by #17
