### ISSUE TITLE
implement "capabilities" introspection.

### ISSUE THREAD

**Issue by YellowOnion** [georgefst/evdev#19]
[python example code](https://python-evdev.readthedocs.io/en/latest/tutorial.html#listing-device-capabilities) & [input.c](https://github.com/gvalkov/python-evdev/blob/master/evdev/input.c#L130)

I'm specifically interested in the Axis and AbsInfo discovery.

(I might add this myself)

**Comment by georgefst** [comment]
See #20.

IIUC, the rest is already covered by `deviceEventTypes` and `deviceHasEvent` (though that API isn't perfect - see #10).

**Comment by YellowOnion** [comment]
Sweet thanks! I'll do some testing.

**Comment by georgefst** [comment]
Are you happy for this to be closed now that #20 is merged?

**Comment by YellowOnion** [comment]
Yes, thanks for your help!
