### ISSUE TITLE
Permissions Advice in Readme

### ISSUE THREAD

**Issue by tannerlegvold** [georgefst/evdev#32]
In the [Permissions section of the Readme in the evdev folder](https://github.com/georgefst/evdev/tree/master/evdev#permissions) the following line is given to add a udev rule for permissions to the `/dev/uinput` device
```
echo 'KERNEL=="uinput", GROUP="uinput", MODE:="0660", OPTIONS+="static_node=uinput"' | sudo tee -a /etc/udev/rules
```
Every time I try this it doesn't work. I think its supposed to be
```
echo 'KERNEL=="uinput", GROUP="uinput", MODE:="0660", OPTIONS+="static_node=uinput"' | sudo tee -a /etc/udev/rules.d/50-uinputRule.rules
```
which just changes the filename. Well, at least, this is what works for me. To trigger a reload of the rules this seems to work instantly
```
sudo udevadm control --reload-rules && sudo udevadm trigger
```
with no relog or reboot necessary assuming you're already a part of the `input` and `uinput` groups (which do require relogs) (and maybe(?) assuming the `uinput` kernel module is loaded) which makes testing easier.

**Comment by georgefst** [comment]
Yeah, the version in the README must have worked for me at some point, but yours is better. It's even what I've got in [another project](https://github.com/georgefst/monpad#linux) which depends on this one.

I'll try out the reloading, thanks. I seem to remember finding nothing that worked for me previously, but it's been a while. And I was much more of a Linux noob when I first wrote this library.

**Comment by georgefst** [comment]
https://github.com/georgefst/evdev/commit/c0d911013f653166e0af43618691a25f8bcaf132
